//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int id { get; set; }
        public int Contract_id { get; set; }
        public int Pet_id { get; set; }
        public int Category_id { get; set; }
        public System.DateTime Term_from { get; set; }
        public System.DateTime Term_up { get; set; }
        public decimal Price { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual Pets Pets { get; set; }
    }
}
