//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooHotel_Staff_Entities : DbContext
    {
        private static ZooHotel_Staff_Entities _context;
        public ZooHotel_Staff_Entities()
            : base("name=ZooHotel_Staff_Entities")
        {
        }

        public static ZooHotel_Staff_Entities Get()
        {
            if (_context == null)
                _context= new ZooHotel_Staff_Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Staffs> Staffs { get; set; }
    }
}
